# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPruebasCTG():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_prueba1RespuestaCompleta(self):
    # Test name: Prueba_1: Respuesta Completa
    # Step # | name | target | value
    # 1 | open | https://huggingface.co/spaces/PDH-INTEGRADOR-GRUPAL-CTG/tp-integrador-ctg | 
    self.driver.get("https://huggingface.co/spaces/PDH-INTEGRADOR-GRUPAL-CTG/tp-integrador-ctg")
    # 2 | setWindowSize | 1382x736 | 
    self.driver.set_window_size(1382, 736)
    # 3 | mouseDownAt | xpath=//html | 1359,389
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 4 | mouseMoveAt | xpath=//html | 1359,389
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 5 | mouseUpAt | xpath=//html | 1359,389
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 6 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 7 | click | xpath=//input[@id='text_input_1'] | 
    self.driver.find_element(By.XPATH, "//input[@id=\'text_input_1\']").click()
    # 8 | type | xpath=//input[@id='text_input_1'] | ¿Qué ventajas ofrece una completación horizontal frente a una vertical en términos de productividad y coning?\n
    self.driver.find_element(By.XPATH, "//input[@id=\'text_input_1\']").send_keys("¿Qué ventajas ofrece una completación horizontal frente a una vertical en términos de productividad y coning?\\n")
    # 9 | click | xpath=//button/div/p | 
    self.driver.find_element(By.XPATH, "//button/div/p").click()
    # 10 | click | xpath=//h3[@id='realiza-tu-consulta-tecnica'] | 
    self.driver.find_element(By.XPATH, "//h3[@id=\'realiza-tu-consulta-tecnica\']").click()
    # 11 | click | xpath=//section/div | 
    self.driver.find_element(By.XPATH, "//section/div").click()
    # 12 | click | xpath=//section/div/div | 
    self.driver.find_element(By.XPATH, "//section/div/div").click()
    # 13 | click | xpath=//section/div | 
    self.driver.find_element(By.XPATH, "//section/div").click()
    # 14 | selectFrame | relative=parent | 
    self.driver.switch_to.default_content()
    # 15 | mouseDownAt | xpath=//html | 1365,1012
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 16 | mouseMoveAt | xpath=//html | 1365,1012
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 17 | mouseUpAt | xpath=//html | 1365,1012
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 18 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 19 | click | xpath=//span/div | 
    self.driver.find_element(By.XPATH, "//span/div").click()
    # 20 | selectFrame | relative=parent | 
    self.driver.switch_to.default_content()
    # 21 | mouseDownAt | xpath=//html | 1365,1508
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 22 | mouseMoveAt | xpath=//html | 1365,1508
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 23 | mouseUpAt | xpath=//html | 1365,1508
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 24 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 25 | click | xpath=//div[13]/div/details/summary/span/div | 
    self.driver.find_element(By.XPATH, "//div[13]/div/details/summary/span/div").click()
    # 26 | selectFrame | relative=parent | 
    self.driver.switch_to.default_content()
    # 27 | mouseDownAt | xpath=//html | 1358,1736
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 28 | mouseMoveAt | xpath=//html | 1358,1736
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 29 | mouseUpAt | xpath=//html | 1358,1736
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 30 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 31 | click | xpath=//div[14]/div/details/summary/span/div | 
    self.driver.find_element(By.XPATH, "//div[14]/div/details/summary/span/div").click()
    # 32 | selectFrame | relative=parent | 
    self.driver.switch_to.default_content()
    # 33 | mouseDownAt | xpath=//html | 1365,1980
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 34 | mouseMoveAt | xpath=//html | 1365,1980
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 35 | mouseUpAt | xpath=//html | 1365,1980
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 36 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 37 | click | xpath=//div[15]/div/details/summary/span/div | 
    self.driver.find_element(By.XPATH, "//div[15]/div/details/summary/span/div").click()
    # 38 | selectFrame | relative=parent | 
    self.driver.switch_to.default_content()
    # 39 | mouseDownAt | xpath=//html | 1363,2188
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 40 | mouseMoveAt | xpath=//html | 1363,2188
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 41 | mouseUpAt | xpath=//html | 1363,2188
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 42 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 43 | click | xpath=//div[16]/div/details/summary/span/div | 
    self.driver.find_element(By.XPATH, "//div[16]/div/details/summary/span/div").click()
    # 44 | selectFrame | relative=parent | 
    self.driver.switch_to.default_content()
    # 45 | mouseDownAt | xpath=//html | 1365,2412
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 46 | mouseMoveAt | xpath=//html | 1365,2412
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 47 | mouseUpAt | xpath=//html | 1365,2412
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
  
  def test_prueba2RespuestaIntemedia(self):
    # Test name: Prueba_2: Respuesta Intemedia
    # Step # | name | target | value
    # 1 | open | https://huggingface.co/spaces/PDH-INTEGRADOR-GRUPAL-CTG/tp-integrador-ctg | 
    self.driver.get("https://huggingface.co/spaces/PDH-INTEGRADOR-GRUPAL-CTG/tp-integrador-ctg")
    # 2 | setWindowSize | 1382x736 | 
    self.driver.set_window_size(1382, 736)
    # 3 | mouseDownAt | xpath=//html | 1359,389
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 4 | mouseMoveAt | xpath=//html | 1359,389
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 5 | mouseUpAt | xpath=//html | 1359,389
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 6 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 7 | click | xpath=//input[@id='text_input_1'] | 
    self.driver.find_element(By.XPATH, "//input[@id=\'text_input_1\']").click()
    # 8 | type | xpath=//input[@id='text_input_1'] | ¿cómo puede distinguirse si un gas es seco, húmedo o de condensado retrógrado en una etapa de evaluación exploratoria?
    self.driver.find_element(By.XPATH, "//input[@id=\'text_input_1\']").send_keys("¿cómo puede distinguirse si un gas es seco, húmedo o de condensado retrógrado en una etapa de evaluación exploratoria?")
    # 9 | click | xpath=//button/div/p | 
    self.driver.find_element(By.XPATH, "//button/div/p").click()
    # 10 | click | xpath=//h3[@id='realiza-tu-consulta-tecnica'] | 
    self.driver.find_element(By.XPATH, "//h3[@id=\'realiza-tu-consulta-tecnica\']").click()
    # 11 | click | xpath=//section/div | 
    self.driver.find_element(By.XPATH, "//section/div").click()
    # 12 | click | xpath=//section/div/div | 
    self.driver.find_element(By.XPATH, "//section/div/div").click()
    # 13 | click | xpath=//section/div | 
    self.driver.find_element(By.XPATH, "//section/div").click()
    # 14 | selectFrame | relative=parent | 
    self.driver.switch_to.default_content()
    # 15 | mouseDownAt | xpath=//html | 1365,1012
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 16 | mouseMoveAt | xpath=//html | 1365,1012
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 17 | mouseUpAt | xpath=//html | 1365,1012
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 18 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 19 | click | xpath=//span/div | 
    self.driver.find_element(By.XPATH, "//span/div").click()
    # 20 | selectFrame | relative=parent | 
    self.driver.switch_to.default_content()
    # 21 | mouseDownAt | xpath=//html | 1365,1508
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 22 | mouseMoveAt | xpath=//html | 1365,1508
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 23 | mouseUpAt | xpath=//html | 1365,1508
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 24 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 25 | click | xpath=//div[13]/div/details/summary/span/div | 
    self.driver.find_element(By.XPATH, "//div[13]/div/details/summary/span/div").click()
    # 26 | selectFrame | relative=parent | 
    self.driver.switch_to.default_content()
    # 27 | mouseDownAt | xpath=//html | 1358,1736
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 28 | mouseMoveAt | xpath=//html | 1358,1736
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 29 | mouseUpAt | xpath=//html | 1358,1736
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 30 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 31 | click | xpath=//div[14]/div/details/summary/span/div | 
    self.driver.find_element(By.XPATH, "//div[14]/div/details/summary/span/div").click()
    # 32 | selectFrame | relative=parent | 
    self.driver.switch_to.default_content()
    # 33 | mouseDownAt | xpath=//html | 1365,1980
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 34 | mouseMoveAt | xpath=//html | 1365,1980
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 35 | mouseUpAt | xpath=//html | 1365,1980
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 36 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 37 | click | xpath=//div[15]/div/details/summary/span/div | 
    self.driver.find_element(By.XPATH, "//div[15]/div/details/summary/span/div").click()
    # 38 | selectFrame | relative=parent | 
    self.driver.switch_to.default_content()
    # 39 | mouseDownAt | xpath=//html | 1363,2188
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 40 | mouseMoveAt | xpath=//html | 1363,2188
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 41 | mouseUpAt | xpath=//html | 1363,2188
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 42 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 43 | click | xpath=//div[16]/div/details/summary/span/div | 
    self.driver.find_element(By.XPATH, "//div[16]/div/details/summary/span/div").click()
    # 44 | selectFrame | relative=parent | 
    self.driver.switch_to.default_content()
    # 45 | mouseDownAt | xpath=//html | 1365,2412
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 46 | mouseMoveAt | xpath=//html | 1365,2412
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 47 | mouseUpAt | xpath=//html | 1365,2412
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
  
  def test_prueba3RespuestaNoEncontrada(self):
    # Test name: Prueba_3: Respuesta No Encontrada
    # Step # | name | target | value
    # 1 | open | https://huggingface.co/spaces/PDH-INTEGRADOR-GRUPAL-CTG/tp-integrador-ctg | 
    self.driver.get("https://huggingface.co/spaces/PDH-INTEGRADOR-GRUPAL-CTG/tp-integrador-ctg")
    # 2 | setWindowSize | 1382x736 | 
    self.driver.set_window_size(1382, 736)
    # 3 | mouseDownAt | xpath=//html | 1359,389
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 4 | mouseMoveAt | xpath=//html | 1359,389
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 5 | mouseUpAt | xpath=//html | 1359,389
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 6 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 7 | click | xpath=//input[@id='text_input_1'] | 
    self.driver.find_element(By.XPATH, "//input[@id=\'text_input_1\']").click()
    # 8 | type | xpath=//div[@id='root']/div/div/div/div/div/section/div/div/div[6]/div/div/div/input | ¿Cómo identificas daño por asfaltenos en campo?
    self.driver.find_element(By.XPATH, "//div[@id=\'root\']/div/div/div/div/div/section/div/div/div[6]/div/div/div/input").send_keys("¿Cómo identificas daño por asfaltenos en campo?")
    # 9 | click | xpath=//button/div/p | 
    self.driver.find_element(By.XPATH, "//button/div/p").click()
    # 10 | click | xpath=//h3[@id='realiza-tu-consulta-tecnica'] | 
    self.driver.find_element(By.XPATH, "//h3[@id=\'realiza-tu-consulta-tecnica\']").click()
    # 11 | click | xpath=//section/div | 
    self.driver.find_element(By.XPATH, "//section/div").click()
    # 12 | click | xpath=//section/div/div | 
    self.driver.find_element(By.XPATH, "//section/div/div").click()
    # 13 | click | xpath=//section/div | 
    self.driver.find_element(By.XPATH, "//section/div").click()
    # 14 | selectFrame | relative=parent | 
    self.driver.switch_to.default_content()
    # 15 | mouseDownAt | xpath=//html | 1365,1012
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 16 | mouseMoveAt | xpath=//html | 1365,1012
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 17 | mouseUpAt | xpath=//html | 1365,1012
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 18 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 19 | click | xpath=//span/div | 
    self.driver.find_element(By.XPATH, "//span/div").click()
    # 20 | selectFrame | relative=parent | 
    self.driver.switch_to.default_content()
    # 21 | mouseDownAt | xpath=//html | 1365,1508
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 22 | mouseMoveAt | xpath=//html | 1365,1508
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 23 | mouseUpAt | xpath=//html | 1365,1508
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 24 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 25 | click | xpath=//div[13]/div/details/summary/span/div | 
    self.driver.find_element(By.XPATH, "//div[13]/div/details/summary/span/div").click()
    # 26 | selectFrame | relative=parent | 
    self.driver.switch_to.default_content()
    # 27 | mouseDownAt | xpath=//html | 1358,1736
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 28 | mouseMoveAt | xpath=//html | 1358,1736
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 29 | mouseUpAt | xpath=//html | 1358,1736
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 30 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 31 | click | xpath=//div[14]/div/details/summary/span/div | 
    self.driver.find_element(By.XPATH, "//div[14]/div/details/summary/span/div").click()
    # 32 | selectFrame | relative=parent | 
    self.driver.switch_to.default_content()
    # 33 | mouseDownAt | xpath=//html | 1365,1980
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 34 | mouseMoveAt | xpath=//html | 1365,1980
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 35 | mouseUpAt | xpath=//html | 1365,1980
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 36 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 37 | click | xpath=//div[15]/div/details/summary/span/div | 
    self.driver.find_element(By.XPATH, "//div[15]/div/details/summary/span/div").click()
    # 38 | selectFrame | relative=parent | 
    self.driver.switch_to.default_content()
    # 39 | mouseDownAt | xpath=//html | 1363,2188
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 40 | mouseMoveAt | xpath=//html | 1363,2188
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 41 | mouseUpAt | xpath=//html | 1363,2188
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 42 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 43 | click | xpath=//div[16]/div/details/summary/span/div | 
    self.driver.find_element(By.XPATH, "//div[16]/div/details/summary/span/div").click()
    # 44 | selectFrame | relative=parent | 
    self.driver.switch_to.default_content()
    # 45 | mouseDownAt | xpath=//html | 1365,2412
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 46 | mouseMoveAt | xpath=//html | 1365,2412
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 47 | mouseUpAt | xpath=//html | 1365,2412
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
  
  def test_prueba4Preguntafueradelcontexto(self):
    # Test name: Prueba_4: Pregunta fuera del contexto
    # Step # | name | target | value
    # 1 | open | https://huggingface.co/spaces/PDH-INTEGRADOR-GRUPAL-CTG/tp-integrador-ctg | 
    self.driver.get("https://huggingface.co/spaces/PDH-INTEGRADOR-GRUPAL-CTG/tp-integrador-ctg")
    # 2 | setWindowSize | 1382x736 | 
    self.driver.set_window_size(1382, 736)
    # 3 | mouseDownAt | xpath=//html | 1359,389
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 4 | mouseMoveAt | xpath=//html | 1359,389
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 5 | mouseUpAt | xpath=//html | 1359,389
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 6 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 7 | click | xpath=//input[@id='text_input_1'] | 
    self.driver.find_element(By.XPATH, "//input[@id=\'text_input_1\']").click()
    # 8 | type | xpath=//div[@id='root']/div/div/div/div/div/section/div/div/div[6]/div/div/div/input | ¿Qué es un pelicano?
    self.driver.find_element(By.XPATH, "//div[@id=\'root\']/div/div/div/div/div/section/div/div/div[6]/div/div/div/input").send_keys("¿Qué es un pelicano?")
    # 9 | click | xpath=//button/div/p | 
    self.driver.find_element(By.XPATH, "//button/div/p").click()
    # 10 | click | xpath=//h3[@id='realiza-tu-consulta-tecnica'] | 
    self.driver.find_element(By.XPATH, "//h3[@id=\'realiza-tu-consulta-tecnica\']").click()
    # 11 | click | xpath=//section/div | 
    self.driver.find_element(By.XPATH, "//section/div").click()
    # 12 | click | xpath=//section/div/div | 
    self.driver.find_element(By.XPATH, "//section/div/div").click()
    # 13 | click | xpath=//section/div | 
    self.driver.find_element(By.XPATH, "//section/div").click()
    # 14 | selectFrame | relative=parent | 
    self.driver.switch_to.default_content()
    # 15 | mouseDownAt | xpath=//html | 1365,1012
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 16 | mouseMoveAt | xpath=//html | 1365,1012
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 17 | mouseUpAt | xpath=//html | 1365,1012
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 18 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 19 | click | xpath=//span/div | 
    self.driver.find_element(By.XPATH, "//span/div").click()
    # 20 | selectFrame | relative=parent | 
    self.driver.switch_to.default_content()
    # 21 | mouseDownAt | xpath=//html | 1365,1508
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 22 | mouseMoveAt | xpath=//html | 1365,1508
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 23 | mouseUpAt | xpath=//html | 1365,1508
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 24 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 25 | click | xpath=//div[13]/div/details/summary/span/div | 
    self.driver.find_element(By.XPATH, "//div[13]/div/details/summary/span/div").click()
    # 26 | selectFrame | relative=parent | 
    self.driver.switch_to.default_content()
    # 27 | mouseDownAt | xpath=//html | 1358,1736
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 28 | mouseMoveAt | xpath=//html | 1358,1736
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 29 | mouseUpAt | xpath=//html | 1358,1736
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 30 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 31 | click | xpath=//div[14]/div/details/summary/span/div | 
    self.driver.find_element(By.XPATH, "//div[14]/div/details/summary/span/div").click()
    # 32 | selectFrame | relative=parent | 
    self.driver.switch_to.default_content()
    # 33 | mouseDownAt | xpath=//html | 1365,1980
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 34 | mouseMoveAt | xpath=//html | 1365,1980
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 35 | mouseUpAt | xpath=//html | 1365,1980
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 36 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 37 | click | xpath=//div[15]/div/details/summary/span/div | 
    self.driver.find_element(By.XPATH, "//div[15]/div/details/summary/span/div").click()
    # 38 | selectFrame | relative=parent | 
    self.driver.switch_to.default_content()
    # 39 | mouseDownAt | xpath=//html | 1363,2188
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 40 | mouseMoveAt | xpath=//html | 1363,2188
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 41 | mouseUpAt | xpath=//html | 1363,2188
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 42 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 43 | click | xpath=//div[16]/div/details/summary/span/div | 
    self.driver.find_element(By.XPATH, "//div[16]/div/details/summary/span/div").click()
    # 44 | selectFrame | relative=parent | 
    self.driver.switch_to.default_content()
    # 45 | mouseDownAt | xpath=//html | 1365,2412
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 46 | mouseMoveAt | xpath=//html | 1365,2412
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 47 | mouseUpAt | xpath=//html | 1365,2412
    element = self.driver.find_element(By.XPATH, "//html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
  
